version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp:latest
    ports:
      - "3000:3000"
    working_dir: /app
    env_file:
      - .env

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file:
      - .env


volumes:
  todo-mysql-data:
